app = "bookkeeper-frontend"
primary_region = "ams"

[build]
  dockerfile = "../Dockerfile.frontend"

[env]
  PORT = "3000"
  ENVIRONMENT = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
