name: Deploy to Fly.io
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          pytest

  deploy:
    name: Deploy apps
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.62
      
      - name: Set environment variables
        run: |
          echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
      
      - name: Deploy Backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          cd backend
          flyctl deploy --remote-only \
            --env VERSION=${GITHUB_SHA::7} \
            --env ENVIRONMENT=production
      
      - name: Deploy Frontend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          cd frontend
          flyctl deploy --remote-only \
            --env API_URL=https://bookkeeper-backend.fly.dev \
            --env VERSION=${GITHUB_SHA::7} \
            --env ENVIRONMENT=production
      
      - name: Run Database Migrations
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl ssh console -a bookkeeper-backend -- "cd /app && alembic upgrade head"
      
      - name: Verify Deployment
        run: |
          sleep 30
          curl -f https://bookkeeper-backend.fly.dev/health || exit 1
          curl -f https://bookkeeper-frontend.fly.dev || exit 1
      
      - name: Notify on Failure
        if: failure()
        run: |
          echo "Deployment failed! Check the logs for details."

  cleanup:
    name: Cleanup Old Deployments
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.62
      
      - name: Remove old deployments
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl releases prune -a bookkeeper-backend --keep 5
          flyctl releases prune -a bookkeeper-frontend --keep 5 